version: '3.8'

networks:
back_default:
  name: back_default

services:
nginx:
  image: buenomarcelo/nginx-stable-alpine:latest
  container_name: back_default_nginx
  hostname: back_default_nginx
  restart: unless-stopped
  depends_on:
    - php
    - phpmyadmin
  ports:
    - 80:80
  volumes:
    - ./:/var/www/html
    - ./nginx/log:/var/log/nginx
    - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
  networks:
    - back_default

php:
  image: buenomarcelo/php-fmp-8.0:latest
  container_name: back_default_php
  hostname: back_default_php
  restart: unless-stopped
  volumes:
    - ./:/var/www/html
  networks:
    - back_default

composer:
  image: buenomarcelo/composer-php-8:latest
  container_name: back_default_composer
  hostname: back_default_composer
  volumes:
    - ./:/var/www/html
  working_dir: /var/www/html
  networks:
    - back_default

artisan:
  image: buenomarcelo/php-fmp-8.0:latest
  container_name: back_default_artisan
  hostname: back_default_artisan
  volumes:
    - ./:/var/www/html
  working_dir: /var/www/html
  entrypoint: ["php", "artisan"]
  networks:
    - back_default

npm:
  image: node:latest
  container_name: back_default_npm
  hostname: back_default_npm
  volumes:
    - ./:/var/www/html
  working_dir: /var/www/html
  entrypoint: ["npm"]
  networks:
    - back_default

mysql:
    image: 'mysql/mysql-server:8.0'
    restart: unless-stopped
    container_name: mysql
    ports:
        - '${DB_PORT}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - ./mysql:/var/lib/mysql
    networks:
        - back_default

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on:
        - mysql
    ports:
        - "8081:80"
    environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    networks:
        - back_default
